apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "keycloak-chart.fullname" . }}
  labels:
    {{- include "keycloak-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "keycloak-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "keycloak-chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.name }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
          env:
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: keycloak-config
                  key: SERVER_PORT
            - name: CONTEXT_PATH
              valueFrom:
                configMapKeyRef:
                  name: keycloak-config
                  key: CONTEXT_PATH
            - name: DATABASE_URI
              valueFrom:
                configMapKeyRef:
                  name: keycloak-config
                  key: DATABASE_URI
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: DATABASE_USERNAME
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: DATABASE_PASSWORD
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 60
            periodSeconds: 5
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 40
            periodSeconds: 5
