apiVersion: v2
name: keycloak-chart
description: An auth service

type: application

version: 0.1.0
appVersion: 0.1.0

dependencies:
  - name: postgresql
    version: 9.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
    tags:
      - auth-database